### PR TITLE
Feature/django 1.9 support

### PR DESCRIPTION
**Pull request by asfaltboy**
Combine commits from #11 and #12 and adds compatibility with older versions.

### CODE REVIEW

**Comment by renou** [comment]
new release for this?

**Comment by asfaltboy** [comment]
Planning a release this weekend, unfortunately didn't get to it last weekend.

**Comment by renou** [comment]
nice! Thank you!

**Comment by macagua** [comment]
:+1:

**Comment by renou** [comment]
django 1.9  does not have "syncdb" anymore. and "migrate" seems not working neither. As a result I cant initialize the tables...

**Pull request merged**
