### PR TITLE
fix input focusing error in chrome

### PR DESCRIPTION
**Pull request by gbezyuk**

### CODE REVIEW

**Comment by asfaltboy** [comment]
Can you provide some more info on what the issue is, and how the fix addresses it?

**Comment by gbezyuk** [comment]
@asfaltboy using Google Chrome v56.0.2924.87 Mac OS, when I hit "save and filter" button, I get an error similar to described here: http://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

**Comment by asfaltboy** [comment]
@gbezyuk Sorry for taking long to get back to you. Strangely, I'm using the same Chrome version on MacOS, and am not getting this error.

Furthermore, if I'm not mistaken, the issue described in the SO question pertains to a field with a `required` attribute; and we don't have any required fields.
Are you perhaps using a custom template for the form which adds a required attribute?

Please don't take this wrong, I am grateful for the PR! I would only like to be able to reproduce the issue before we resolve it with this sort of workaround, to make sure we're fixing it properly.

**Comment by asfaltboy** [comment]
I reviewed the issue on my local environment after upgrading to Django 1.10, and it manifests. Seems Django admin templates were updated to use "required" fields to take advantage of client side validation (at least for required fields), which looks something like this:

screen shot 2017-04-02 at 14 00 13

I kind of like this behavior and want to keep it; however using `novalidate` attribute effectively turns HTML5 validation off ... which results in simple server side validation

screen shot 2017-04-02 at 14 03 11

While technically both work, the client side validation failure prevents submission entirely, so it seems like it's a good workaround until we figure the proper fix for client side validation.

Just to note, we copy the fields frontend behavior from Django-admin inline formsets, by copying `inlines.js`. I've tried updating our `orig_inlines.js` to the latest from django 1.10 however the issue was not resolved. Seems that Django 1.10 also uses `novalidate` in change/changelist forms, due to other issues with client side validation across different browsers (refs: [Django#26982][1] and [Django#23075][2].

[1]: https://code.djangoproject.com/ticket/26982
[2]: https://code.djangoproject.com/ticket/23075

**Comment by gbezyuk** [comment]
Sorry for delay and thank you for both your research and merging my workaround.

**Pull request merged**
