### PR TITLE
fixes and testing for Django 2.1

### LINKED ISSUE #86: ValueError while creating empty form
Hi.
After upgrading to Django 2.1 and changing to the advance_filters development branch I got the following error.
...
 File "/usr/local/lib/python3.6/site-packages/advanced_filters/forms.py", line 236, in forms
    forms.append(self.empty_form)  # add initial empty form
  **File "/usr/local/lib/python3.6/site-packages/advanced_filters/forms.py", line 218, in empty_form**
    empty_permitted=True,
  File "/usr/local/lib/python3.6/site-packages/advanced_filters/forms.py", line 193, in __init__
    super(AdvancedFilterQueryForm, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 104, in __init__
    'The empty_permitted and use_required_attribute arguments may '
**ValueError: The empty_permitted and use_required_attribute arguments may not both be True**.
...
After debugging I found out that in the **empty_form** method inside advanced_filters/forms.py in the form constructor is probably missing the the **use_required_attribute=False** parameter.
After I added it, the advance_filters restarted to work.
This issue happens because in the django BaseForm __init__ the **use_required_attribute** argument is set to true by default.

Could somebody add **use_required_attribute=False** to the form constructor in the empty_form method?

Thanks

### PR DESCRIPTION
**Pull request by PetrDlouhy**
fixes #86

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@asfaltboy `pytest-django` is no longer compatible with Django < 1.8. So it is impossible to test in Django 1.5 - 2.1 with one version of `pytest-django`. Do you think, that the older versions could be dropped, or should I install different version for different Django version?

**Comment by PetrDlouhy** [comment]
@asfaltboy Nevermind. I fixed it in for all versions. Please merge.

**Comment by asfaltboy** [comment]
Thanks for the PR @PetrDlouhy ! Sorry for the delayed response.

I still prefer to try and remove `empty_form` and add `model_fields` to our `get_form_kwargs` to have less things to maintain (the more we override, the more we need to keep patching it on version upgrades :/ ).

**Comment by PetrDlouhy** [comment]
@asfaltboy Done.

BTW: I think after releasing this it is time to drop unsupported Django versions and clean the code of obsolete code variants.

**Pull request merged**
