### PR TITLE
Improvements about Django 1.9 support

### PR DESCRIPTION
**Pull request by macagua**
- Fixed a Warning for Django import

- Fixed some errors for Django 1.9 support

### CODE REVIEW

**Comment by asfaltboy** [comment]
Hi @macagua, thank you for taking the time to prepare this PR!  Please note that @schuyler's django19 branch is more or less in line with yours and includes a few more changes, so I am reviewing both branches and rebasing against `develop` as it has better test coverage.

[1]: https://github.com/modlinltd/django-advanced-filters/compare/develop...schuyler1d:django19

**Comment by macagua** [comment]
Hi @asfaltboy but close this PR and merge this improvements about **develop** branch? an again send by a new PR?

**Comment by asfaltboy** [comment]
No need for new PR, I'm working on the merge. I would like to keep supporting older Django versions (for now) so I'm fixing all these use cases.

**Comment by macagua** [comment]
Ok @asfaltboy thanks!

**Pull request closed without merging**
